CREATE TABLE TblFornecedor(
    NrCNPJ             CHAR(14)        NOT NULL,
    nmRazaoSocial      VARCHAR(100)    NOT NULL,
    DsEndereco         VARCHAR(100),
    DsCidade           VARCHAR(60),
    DsEstado           CHAR(2),
    DsCEP              CHAR(10),
    DsInscEstadual     VARCHAR(15),
    DsInscMunicipal    VARCHAR(16),
    DtCadastro         DATETIME,
    PRIMARY KEY (NrCNPJ)
);



-- 
-- TABLE: TblMaterial 
--

CREATE TABLE TblMaterial(
    CdMaterial        CHAR(13)         NOT NULL,
    DsMaterial        VARCHAR(100),
    QtdMinima         DECIMAL(7, 3),
    QtdMaxima         DECIMAL(7, 3),
    DsLocal           VARCHAR(100),
    CdTipoMaterial    INTEGER          NOT NULL,
    PRIMARY KEY (CdMaterial)
);



-- 
-- TABLE: TblOrcaItem 
--

CREATE TABLE TblOrcaItem(
    NrPedido      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NrCNPJ        CHAR(14)          NOT NULL,
    CdMaterial    CHAR(13)          NOT NULL,
    VlMaterial    DECIMAL(10, 2),
    PRIMARY KEY (NrPedido, NrCNPJ, CdMaterial)
);



-- 
-- TABLE: TblOrcamento 
--

CREATE TABLE TblOrcamento(
    NrPedido     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NrCNPJ       CHAR(14)  NOT NULL,
    DtEnvio      DATETIME,
    DtRetorno    DATETIME,
    PRIMARY KEY (NrPedido, NrCNPJ)
);



-- 
-- TABLE: TblPedido 
--

CREATE TABLE TblPedido(
    NrPedido    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DsPedido    DATETIME,
    PRIMARY KEY (NrPedido)
);



-- 
-- TABLE: TblPedidoItem 
--

CREATE TABLE TblPedidoItem(
    NrPedido      INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    CdMaterial    CHAR(13)         NOT NULL,
    NrQuant       DECIMAL(7, 3),
    PRIMARY KEY (NrPedido, CdMaterial)
);



-- 
-- TABLE: TblTipoMaterial 
--

CREATE TABLE TblTipoMaterial(
    CdTipoMaterial   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DsTipoMaterial    VARCHAR(100)    NOT NULL,
    PRIMARY KEY (CdTipoMaterial)
);



-- 
-- TABLE: TblMaterial 
--

ALTER TABLE TblMaterial ADD CONSTRAINT RefTblTipoMaterial1 
    FOREIGN KEY (CdTipoMaterial)
    REFERENCES TblTipoMaterial(CdTipoMaterial)
;


-- 
-- TABLE: TblOrcaItem 
--

ALTER TABLE TblOrcaItem ADD CONSTRAINT RefTblOrcamento6 
    FOREIGN KEY (NrPedido, NrCNPJ)
    REFERENCES TblOrcamento(NrPedido, NrCNPJ)
;

ALTER TABLE TblOrcaItem ADD CONSTRAINT RefTblMaterial7 
    FOREIGN KEY (CdMaterial)
    REFERENCES TblMaterial(CdMaterial)
;


-- 
-- TABLE: TblOrcamento 
--

ALTER TABLE TblOrcamento ADD CONSTRAINT RefTblPedido4 
    FOREIGN KEY (NrPedido)
    REFERENCES TblPedido(NrPedido)
;

ALTER TABLE TblOrcamento ADD CONSTRAINT RefTblFornecedor5 
    FOREIGN KEY (NrCNPJ)
    REFERENCES TblFornecedor(NrCNPJ)
;


-- 
-- TABLE: TblPedidoItem 
--

ALTER TABLE TblPedidoItem ADD CONSTRAINT RefTblPedido2 
    FOREIGN KEY (NrPedido)
    REFERENCES TblPedido(NrPedido)
;

ALTER TABLE TblPedidoItem ADD CONSTRAINT RefTblMaterial3 
    FOREIGN KEY (CdMaterial)
    REFERENCES TblMaterial(CdMaterial)
;


